version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3138"
    ports:
      - "3138:3000"
    environment:
      - NODE_ENV=production
      - POSTGRES_URL=postgresql://postgres:mysecretpassword@db:5432/postgres
      - AUTH_SECRET=${AUTH_SECRET}
      - XAI_API_KEY=${XAI_API_KEY}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
    depends_on:
      - db
      - init
    restart: unless-stopped

  init:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm db:migrate
    environment:
      - NODE_ENV=production
      - POSTGRES_URL=postgresql://postgres:mysecretpassword@db:5432/postgres
    depends_on:
      - db
    restart: "no"

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    volumes:
      - ../files/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 